#ifndef(__user_colors_inc)
#declare __user_colors_inc = true;

//#ifndef(col_brd)
//#declare col_brd = texture{pigment{color DarkGreen}}
//#end
#ifndef(col_wrs)
#declare col_wrs = texture{pigment{color rgb<0,173,0>}}
#end
#ifndef(col_pds)
#declare col_pds = texture{T_Silver_5A}
#end
#ifndef(col_hls)
#declare col_hls = texture{pigment{ color Black}}
#end
#ifndef(col_bgr)
#declare col_bgr = Gray50;
#end
#ifndef(col_slk)
#declare col_slk = texture{pigment{color White}}
#end
#ifndef(col_thl)
#declare col_thl = texture{T_Silver_5A}
#end
#ifndef(col_pol)
#declare col_pol = col_wrs
#end

#end
